" Explicitly add the XDG config directory to Vim's runtimepath
set runtimepath^=$HOME/.config/vim
set runtimepath+=$HOME/.config/vim/after

set hidden
set nocp
set grepprg=rg\ --vimgrep\ --smart-case\ --follow
set relativenumber number

filetype plugin on
call plug#begin('~/.config/vim/plugged')
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
call plug#end()

nnoremap <silent> <C-p> :Files<CR>
nnoremap <silent> <C-f> :Rg<CR>
nnoremap <silent> <Leader>b :Buffers<CR>
