" Explicitly add the XDG config directory to Vim's runtimepath
set runtimepath^=$HOME/.config/vim
set runtimepath+=$HOME/.config/vim/after

set hidden
set nocp
set grepprg=rg\ --vimgrep\ --smart-case\ --follow
set relativenumber number
set directory^=$HOME/.local/state/vim/swap//
 
filetype plugin on
call plug#begin('~/.config/vim/plugged')
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'dense-analysis/ale'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'preservim/nerdtree'
call plug#end()

" Set leader key to Space
let mapleader = " "
nnoremap <silent> <C-p> :Files<CR>
nnoremap <silent> <C-f> :Rg<CR>
nnoremap <silent> \b :Buffers<CR>
nnoremap \x :bnext<CR>
nnoremap \z :bprevious<CR>
nnoremap <silent> <leader>B :NERDTreeFind<CR>
nnoremap <silent> <leader>b :NERDTreeToggle<CR>
nnoremap <C-j> 10j
nnoremap <C-k> 10k
autocmd FileType nerdtree nnoremap <buffer> <C-j> 10j
autocmd FileType nerdtree nnoremap <buffer> <C-k> 10k
inoremap jk <Esc>
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm() : "\<CR>"
inoremap <silent><expr> <Tab>   coc#pum#visible() ? coc#pum#next(1) : "\<Tab>"
inoremap <silent><expr> <S-Tab> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"
inoremap <silent><expr> <Esc> coc#pum#visible() ? coc#pum#cancel() : "\<Esc>"
nnoremap <leader>r :source $MYVIMRC<CR>
autocmd FileType fzf inoremap <buffer> jk <Esc>
nmap <silent> gd <Plug>(coc-definition)

" Enable ALE
let g:ale_linters = {
\   'python': ['pyright', 'mypy', 'flake8', 'ruff']
\}
let g:ale_fixers = {
\   'python': ['isort', 'autopep8']
\}
let g:ale_python_pyright_executable = 'pyright'
let $FZF_DEFAULT_OPTS = '
\ --bind alt-j:down,alt-k:up
\ --bind ctrl-d:half-page-down,ctrl-u:half-page-up
\ --bind ctrl-n:down,ctrl-p:up
\ '
