unbind r
bind r source-file ~/.config/tmux/tmux.conf

unbind m
bind m resize-pane -Z  

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r h resize-pane -L 5
bind -r l resize-pane -R 5
bind ! run-shell '
wid=$(tmux display-message -p "#{window_id}")
tmux break-pane -d -PF "#{pane_id}" >> /tmp/tmux_hidden_$wid
'

bind @ run-shell '
wid=$(tmux display-message -p "#{window_id}")
file=/tmp/tmux_hidden_$wid

[ -f "$file" ] || exit

pane=$(tail -n 1 "$file")

# remove last line (mac + linux compatible)
sed -i "" -e "$d" "$file" 2>/dev/null || sed -i -e "$d" "$file"

# only restore if pane still exists
tmux list-panes -a -F "#{pane_id}" | grep -q "$pane" && \
  tmux join-pane -s "$pane"
'

set -g mouse on
set -g focus-events on
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane


set-option -g status-position top
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set -g @plugin 'dracula/tmux'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'kristijan/fzf-pane-switch.tmux'
set -g @dracula-show-powerline true
set -g @dracula-show-left-sep 
set -g @dracula-show-left-icon "#S"
set -g @dracula-colors "gray='#111218' dark_purple='#2563eb' light_purple='#60a5fa'"
set -g @dracula-plugins "cwd"
set -g @fzf_pane_switch_list-panes-format "session_name window_name pane_title"

run '~/.config/tmux/plugins/tpm/tpm'
